# vim: ts=2 sw=2 et ft=toml

[theme]
  name = "gruvbox-dark"

[icons]
  name = "awesome"

[icons.overrides]
  time = "  "
  cpu = "  "

[[block]]
  block = "pacman"
  interval = 600

[[block]]
  block = "disk_space"
  path = "/"
  alias = "/"
  info_type = "available"
  unit = "GB"
  interval = 20

[[block]]
  block = "disk_space"
  path = "/home"
  alias = "/home"
  info_type = "available"
  unit = "GB"
  interval = 20

[[block]]
  block = "net"
  device = "enp0s31f6"
  ssid = false
  ip = true
  speed_up = false
  graph_up = false
  speed_down = false
  graph_down = false
  interval = 1

[[block]]
  block = "net"
  device = "wlp1s0"
  ssid = true
  ip = true
  speed_up = false
  graph_up = false
  speed_down = false
  graph_down = false
  interval = 1

[[block]]
  block = "cpu"
  interval = 1
  format = "{barchart} {utilization}% {frequency}GHz"

[[block]]
  block = "battery"
  interval = 10
  format = "{percentage}% {time}"

[[block]]
  block = "sound"

[[block]]
  block = "backlight"

[[block]]
  block = "temperature"
  collapsed = false
  interval = 10
  format = "{average}°C"
  chip = "*-isa-*"

[[block]]
  block = "time"
  format = "%A %v %T"
  timezone = "Europe/Zurich"
  interval = 1
